### ISSUE TITLE
db Definition

### ISSUE THREAD

**Issue by geopayme** [DRDoGE/dogegiftcards#1]
Hello,

I was looking at the project and I cant find where you actually define the db for the script.

I believe the sql file to create the DB is missing or I cant seem to find it in the existing code.

**Comment by DRDoGE** [comment]
Hi,  

really sorry for not getting back to you earlier, but I abandoned the project (and this account) one year ago.  The code in this project is of really bad quality and you will be better off rewriting it from scratch as it doesn't adhere to any coding standards at all.  Though it may be helpful to get an idea of the features I had in mind.

However, I have found uncommitted changes in my local repository and will commit them now. The db structure is at the bottom of the readme.

**Comment by geopayme** [comment]
Thanks...

**Comment by geopayme** [comment]
I will update you when I revamp the code! - cheers

**Comment by DRDoGE** [comment]
Great! I really liked the idea back then, but it didn't get enough traction. Looking forward to see what you make of it. :)
